Update needs.yaml

diff --git a/.github/workflows/needs.yaml b/.github/workflows/needs.yaml
--- a/.github/workflows/needs.yaml
+++ b/.github/workflows/needs.yaml
@@ -18,9 +18,10 @@ jobs:
   job3:
     runs-on: ubuntu-latest
     steps:
-    - name: |
-      echo "job3 failed"
-      exit 1
+    - name: echo
+      run: |
+        echo "job3 failed"
+        exit 1
 
   job4:
     runs-on: ubuntu-latest
